#!/bin/bash

# Check for prerequisite packages

MAINTAINER=1

UBUNTUPKGS=( \
  "binutils" "g++" "gcc" "make" "libmotif-dev" "libx11-dev" "libxpm-dev" \
  "libxt-dev" "libxpm-dev" "libncurses-dev" "gdb" "fonts-liberation" \
  )
UBUNTUDEVPKGS=( \
  "automake" "autoconf" "libtool" "bison" "flex" "texinfo" "netpbm" \
  "texlive-font-utils" "texlive-latex-base" \
  )

NEEDED=""

if grep Ubuntu /etc/os-release > /dev/null; then
  DISTRO="UBUNTU"
  INSTALLED=$(dpkg -l | cut -d ' ' -f 3 | cut -d ':' -f 1)
  INSTALLED=" $INSTALLED "
elif grep Fedora /etc/os-release > /dev/null; then
  DISTRO="FEDORA"
else
  DISTRO="UNKNOWN"
fi

if [ "$DISTRO" = "UNKNOWN" ]; then
  echo "Cannot check pre-req's for $DISTRO distro"
  exit 1
fi

if [ "$DISTRO" = "UBUNTU" ]; then
  echo "Checking pre-req's for $DISTRO distro"
  echo ""

  if [ $MAINTAINER = 1 ]; then
    PKGS=( ${UBUNTUPKGS[*]} ${UBUNTUDEVPKGS[*]} )
  else
    PKGS=( ${UBUNTUPKGS[*]} )
  fi
  
  for PKG in ${PKGS[@]}
  do 
    if echo $INSTALLED | grep " $PKG " &> /dev/null ; then
      echo "$PKG installed"
    else
      echo "$PKG not installed"
      NEEDED="$NEEDED $PKG"
    fi
  done

fi

echo " "
if [ "$NEEDED" == "" ] ; then
  echo "All prerequsite packages installed"
else 
  echo "The following packages need to be installed:"
  echo $NEEDED
fi
